#!/usr/bin/env bash
set -euo pipefail

INSTALL_ROOT="C:/Users/chaso/AppData/Local/DialUp/sdk-plugin/include"

find "$INSTALL_ROOT" -type f \( -name "*.h" -o -name "*.cpp" \) | while read -r f; do
	tmp=$(mktemp);
	{
				echo "// ============================================";
				echo "// Auto-generated by DialUp SDK Generator";
				echo "// DO NOT MODIFY - Changes will be overwritten";
				echo "// ============================================";
		echo;
		sed 's/\r$//' "$f";
	} > "$tmp";
	mv "$tmp" "$f";
done
